# Site settings
title: ▦ Milesss
email: happlex@qq.com
qq: 420079939
description: > # this means to ignore newlines until "baseurl:"
  终于有自己的博客啦！
  晚些时候可能会发点随笔和一些技术教程。
  欢迎大家光临！~
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://happlex.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  Happlex
zhihu_username: Happlex
pages: tech caprice about

# Build settings
markdown: redcarpet
